version: '3.2'

services:
  ###################################################
  # DC1
  ###################################################
  # Storage 1
  consul1:
    image: consul:1.1.0
    command: agent -server -bootstrap -client=0.0.0.0 -ui
    environment:
     - CONSUL_LOCAL_CONFIG={ "datacenter":"dc1" }
    hostname: consul1
    ports:
      - 8501:8500

  minio1:
    image: minio/minio:RELEASE.2018-05-04T23-13-12Z
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_REGION: us-east-1
    entrypoint: sh
    command: -c "mkdir -p /data/storage && /usr/bin/minio server /data"

  aerospike1:
    image: aerospike/aerospike-server:3.15.1.4
    command: [ "--config-file","/run/secrets/storage_aerospike.conf"]
    secrets:
    - source: storage_conffile
      target: storage_aerospike.conf
      mode: 0440

  storage1:
    image: devchallenge/storage
    ports:
      - 8080:8080
    environment:
      S3_ENDPOINT: http://minio1:9000
      ACCESS_KEY: minio
      SECRET_KEY: minio123
      S3_REGION: us-east-1
      S3_BUCKET: storage
      SERVICE_HOST: storage1
      SERVICE_ID: storage1
      SERVICE_REGION: us-east-1
      CONSUL_HOST: consul1
      CONSUL_PORT: 8500
      AEROSPIKE_HOST: aerospike1
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USER: rabbit
      AMQP_PASSWORD: rabbit123
      SYNC_URI: http://sync_server:8080

  # Sync app
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit123
    ports:
      - 15672:15672

  aerospike_for_sync:
    image: aerospike/aerospike-server:3.15.1.4
    command: [ "--config-file","/run/secrets/sync_aerospike.conf"]
    secrets:
    - source: sync_conffile
      target: sync_aerospike.conf
      mode: 0440

  sync_server:
    image: devchallenge/sync
    environment:
      CONSUL_HOST: consul1
      CONSUL_PORT: 8500
      AEROSPIKE_HOST: aerospike_for_sync
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USER: rabbit
      AMQP_PASSWORD: rabbit123
      REPLICATION_FACTOR: 1

  # end Sync app

  ###################################################

  ###################################################
  # DC1
  ###################################################
  # Storage 2
  consul2:
    image: consul:1.1.0
    command: agent -server -retry-join-wan consul1 -bootstrap -client 0.0.0.0 -ui
    hostname: consul2
    environment:
     - CONSUL_LOCAL_CONFIG={ "datacenter":"dc2" }

  minio2:
    image: minio/minio:RELEASE.2018-05-04T23-13-12Z
    ports:
      - 9001:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_REGION: eu-west-1
    entrypoint: sh
    command: -c "mkdir -p /data/storage && /usr/bin/minio server /data"

  aerospike2:
    image: aerospike/aerospike-server:3.15.1.4
    command: [ "--config-file","/run/secrets/storage_aerospike.conf"]
    secrets:
    - source: storage_conffile
      target: storage_aerospike.conf
      mode: 0440

  storage2:
    image: devchallenge/storage
    ports:
      - 8081:8080
    environment:
      S3_ENDPOINT: http://minio2:9000
      ACCESS_KEY: minio
      SECRET_KEY: minio123
      S3_REGION: eu-west-1
      S3_BUCKET: storage
      SERVICE_HOST: storage2
      SERVICE_ID: storage2
      SERVICE_REGION: eu-west-1
      CONSUL_HOST: consul2
      CONSUL_PORT: 8500
      AEROSPIKE_HOST: aerospike2
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USER: rabbit
      AMQP_PASSWORD: rabbit123
      SYNC_URI: http://sync_server:8080

  # End Storage 2

  # Storage 2
  consul3:
    image: consul:1.1.0
    command: agent -server -retry-join consul2 -client 0.0.0.0 -ui
    hostname: consul3
    environment:
     - CONSUL_LOCAL_CONFIG={ "datacenter":"dc2" }

  minio3:
    image: minio/minio:RELEASE.2018-05-04T23-13-12Z
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_REGION: eu-west-2
    entrypoint: sh
    command: -c "mkdir -p /data/storage && /usr/bin/minio server /data"

  aerospike3:
    image: aerospike/aerospike-server:3.15.1.4
    command: [ "--config-file","/run/secrets/storage_aerospike.conf"]
    secrets:
    - source: storage_conffile
      target: storage_aerospike.conf
      mode: 0440

  storage3:
    image: devchallenge/storage
    ports:
      - 8082:8080
    environment:
      S3_ENDPOINT: http://minio3:9000
      ACCESS_KEY: minio
      SECRET_KEY: minio123
      S3_REGION: eu-west-2
      S3_BUCKET: storage
      SERVICE_HOST: storage3
      SERVICE_ID: storage3
      SERVICE_REGION: eu-west-2
      CONSUL_HOST: consul3
      CONSUL_PORT: 8500
      AEROSPIKE_HOST: aerospike3
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USER: rabbit
      AMQP_PASSWORD: rabbit123
      SYNC_URI: http://sync_server:8080

  # End Storage 2


secrets:
  storage_conffile:
    file: aerospike/storage_aerospike.conf
  sync_conffile:
    file: aerospike/sync_aerospike.conf


